package:
  name: modrefiner
  version: 0.1

source:
  url: https://zhanggroup.org/ModRefiner/ModRefiner-w.zip # [win]
  
build:
  number: 0
  script:
    - "mkdir %PREFIX%\\bin & move * %PREFIX%\\bin" # [win]

test:
  commands:
    - ModRefiner-w\emrefinement.exe -h # [win]
