package:
  name: modrefiner
  version: 0.1

source:
  url: https://zhanggroup.org/ModRefiner/ModRefiner-w.zip # [win]
  
build:
  number: 0
  script:
    - "mkdir %PREFIX%\\bin & xcopy /e /v %SRC_DIR% %PREFIX%\\bin" # [win]

test:
  commands:
    - which emrefinement.exe && which mcrefinement.exe # [win]
